// Blog Categories Configuration
import { UtensilsCrossed, Dumbbell, Heart, TrendingUp, Plane, Sparkles } from "lucide-react";

export const CATEGORIES = [
  {
    id: "food",
    name: "Food",
    slug: "food",
    icon: <UtensilsCrossed className="h-5 w-5" />,
    description: "Delicious recipes, culinary adventures, and food culture from around the world.",
    colorClass: "category-food",
  },
  {
    id: "fitness",
    name: "Fitness",
    slug: "fitness",
    icon: <Dumbbell className="h-5 w-5" />,
    description: "Workouts, training tips, and everything to help you achieve your fitness goals.",
    colorClass: "category-fitness",
  },
  {
    id: "health",
    name: "Health",
    slug: "health",
    icon: <Heart className="h-5 w-5" />,
    description: "Wellness advice, mental health, and tips for a healthier lifestyle.",
    colorClass: "category-health",
  },
  {
    id: "wealth",
    name: "Wealth",
    slug: "wealth",
    icon: <TrendingUp className="h-5 w-5" />,
    description: "Financial wisdom, investment strategies, and paths to prosperity.",
    colorClass: "category-wealth",
  },
  {
    id: "travel",
    name: "Travel",
    slug: "travel",
    icon: <Plane className="h-5 w-5" />,
    description: "Explore destinations, travel guides, and adventures across the globe.",
    colorClass: "category-travel",
  },
  {
    id: "spirituality",
    name: "Spirituality",
    slug: "spirituality",
    icon: <Sparkles className="h-5 w-5" />,
    description: "Inner peace, mindfulness, and spiritual growth for the soul.",
    colorClass: "category-spirituality",
  },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

// Mock Articles for Frontend Demo
export const MOCK_ARTICLES = [
  {
    id: "1",
    title: "10 Quick Healthy Breakfast Ideas for Busy Mornings",
    slug: "healthy-breakfast-ideas",
    category: "food",
    excerpt: "Start your day right with these nutritious and delicious breakfast recipes that take less than 15 minutes to prepare.",
    content: "<p>Starting your day with a healthy breakfast sets the tone for the entire day...</p>",
    coverImage: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800",
    pdfUrl: "/downloads/healthy-breakfast.pdf",
    createdAt: "2024-01-15",
    author: "Chef Maria",
  },
  {
    id: "2",
    title: "The Ultimate Home Workout Routine for Beginners",
    slug: "home-workout-beginners",
    category: "fitness",
    excerpt: "No gym? No problem! This comprehensive guide will help you build strength and endurance from the comfort of your home.",
    content: "<p>Getting fit doesn't require expensive gym memberships or fancy equipment...</p>",
    coverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    pdfUrl: "/downloads/home-workout.pdf",
    createdAt: "2024-01-12",
    author: "Coach Mike",
  },
  {
    id: "3",
    title: "Understanding Mental Health: A Complete Guide",
    slug: "mental-health-guide",
    category: "health",
    excerpt: "Breaking the stigma and understanding the importance of mental wellness in our daily lives.",
    content: "<p>Mental health is just as important as physical health...</p>",
    coverImage: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
    pdfUrl: "/downloads/mental-health.pdf",
    createdAt: "2024-01-10",
    author: "Dr. Sarah Chen",
  },
  {
    id: "4",
    title: "Building Your First Investment Portfolio",
    slug: "first-investment-portfolio",
    category: "wealth",
    excerpt: "A beginner-friendly guide to starting your investment journey with confidence and smart strategies.",
    content: "<p>Investing can seem intimidating at first, but it doesn't have to be...</p>",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800",
    pdfUrl: "/downloads/investment-guide.pdf",
    createdAt: "2024-01-08",
    author: "James Wilson",
  },
  {
    id: "5",
    title: "Hidden Gems: Unexplored Destinations in Southeast Asia",
    slug: "southeast-asia-hidden-gems",
    category: "travel",
    excerpt: "Discover breathtaking locations off the beaten path that will make your next adventure unforgettable.",
    content: "<p>Southeast Asia is home to some of the world's most beautiful destinations...</p>",
    coverImage: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800",
    pdfUrl: "/downloads/southeast-asia.pdf",
    createdAt: "2024-01-05",
    author: "Travel Nomad",
  },
  {
    id: "6",
    title: "Meditation for Beginners: Finding Inner Peace",
    slug: "meditation-beginners",
    category: "spirituality",
    excerpt: "Learn the basics of meditation and start your journey towards mindfulness and inner tranquility.",
    content: "<p>Meditation is a practice that has been used for thousands of years...</p>",
    coverImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
    pdfUrl: "/downloads/meditation-guide.pdf",
    createdAt: "2024-01-03",
    author: "Guru Priya",
  },
  {
    id: "7",
    title: "Authentic Italian Pasta: From Scratch",
    slug: "italian-pasta-scratch",
    category: "food",
    excerpt: "Master the art of making fresh pasta with traditional Italian techniques passed down through generations.",
    content: "<p>There's nothing quite like homemade pasta...</p>",
    coverImage: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800",
    pdfUrl: "/downloads/italian-pasta.pdf",
    createdAt: "2024-01-01",
    author: "Chef Marco",
  },
  {
    id: "8",
    title: "HIIT Training: Maximize Results in Minimum Time",
    slug: "hiit-training-guide",
    category: "fitness",
    excerpt: "Discover how High-Intensity Interval Training can transform your fitness routine and boost your metabolism.",
    content: "<p>HIIT has revolutionized the fitness industry...</p>",
    coverImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
    pdfUrl: "/downloads/hiit-training.pdf",
    createdAt: "2023-12-28",
    author: "Coach Mike",
  },
];

export type Article = (typeof MOCK_ARTICLES)[number];
